site_name: SOC2-Playbook
nav:
    - Home: index.md
    - About: about.md
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    
theme: material
#### list of themes ####
## material
## theme: readthedocs
