site_name: SOC Playbook
nav:
    - Home: index.md
    - Trust Service Category: TrustServicesCategories.md
    - Common Trust Service Criteria:
        - Control Environment: 
            - CC1.1: tsc/cc1-1.md
            - CC1.2: tsc/cc1-2.md
            - CC1.3: tsc/cc1-3.md
            - CC1.4: tsc/cc1-4.md
        - Information and Communication:
            - CC2.1: tsc/cc2-1.md
            - CC2.2: tsc/cc2-2.md
            - CC2.3: tsc/cc2-3.md
        - Risk Assessment:
            - CC3.1: tsc/cc3-1.md
            - CC3.2: tsc/cc3-2.md
            - CC3.3: tsc/cc3-3.md
            - CC3.4: tsc/cc3-4.md
        - Monitoring Activities:
            - CC4.1: tsc/cc4-1.md
            - CC4.2: tsc/cc4-2.md
        - Control Activities:
            - CC5.1: tsc/cc5-1.md
            - CC5.2: tsc/cc5-2.md
            - CC5.3: tsc/cc5-3.md
        - Logical and Physical Access Controls:
            - CC6.1: tsc/cc6-1.md
            - CC6.2: tsc/cc6-2.md
            - CC6.3: tsc/cc6-3.md
            - CC6.4: tsc/cc6-4.md
            - CC6.5: tsc/cc6-5.md
            - CC6.6: tsc/cc6-6.md
            - CC6.7: tsc/cc6-7.md
            - CC6.8: tsc/cc6-8.md
        - System Operations:
            - CC7.1: tsc/cc7-1.md
            - CC7.2: tsc/cc7-2.md
            - CC7.3: tsc/cc7-3.md
            - CC7.4: tsc/cc7-4.md
            - CC7.5: tsc/cc7-5.md
        - ChangRisk Mitigation Management CC8.1: tsc/cc8-1.md 
        - Risk Mitigation:
            - CC9.1: tsc/cc9-1.md
            - CC9.2: tsc/cc9-2.md
    - Trust Service Criteria - Availability:
        - A1.1: atsc/a1-1.md
        - A1.2: atsc/a1-2.md
        - A1.3: atsc/a1-3.md    
    - Trust Service Criteria - Confidentiality:
        - C1.1: ctsc/c1-1.md
        - C1.2: ctsc/c1-2.md
    -  Trust Service Criteria - Processing Integrity:
        - PI1.1: pitsc/pi1-1.md
        - PI1.2: pitsc/pi1-2.md
        - PI1.3: pitsc/pi1-3.md
        - PI1.4: pitsc/pi1-4.md
        - PI1.5: pitsc/pi1-5.md
            
    - SOC 1 Report: about.md
    - SOC 2 type 1 Report: about.md
    - SOC 2 type 2 Report: about.md
    - SOC 3 Report: about.md
    - About: about.md
    
copyright: Copyright &copy; 2023 Washington GT.
    
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true   
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
    
theme: 
    name: material
    features:
        - content.tabs.link

#### list of themes ####
## material
## theme: readthedocs

extra:
  analytics:
    provider: google
    property: G-FVH8RBS1KG
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/WashingtonGT/soc2-playbook/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
