site_name: SOC2-Playbook
nav:
    - Home: index.md
    - About: about.md
    
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
    
theme: material
#### list of themes ####
## material
## theme: readthedocs
